# Generated by Django 3.1 on 2020-12-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_following'),
        ('fleeks', '0002_auto_20201217_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleeksimage',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
