# Generated by Django 3.1 on 2020-12-20 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleeks', '0003_auto_20201218_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleek',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleeks.fleek'),
        ),
    ]
