# Generated by Django 3.1 on 2020-12-20 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleeks', '0004_auto_20201220_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='fleek_user', through='fleeks.FleeksLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fleek',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleeks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fleeksimage',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fleekslike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
