# Generated by Django 3.1 on 2020-12-20 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_following'),
        ('fleeks', '0005_auto_20201220_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='fleek_user', through='fleeks.FleeksLike', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='fleek',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleeks', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='fleeksimage',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='fleekslike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
