# Generated by Django 3.1 on 2020-12-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_following'),
        ('fleeks', '0007_auto_20201222_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleek',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleeks', to='accounts.profile'),
        ),
    ]
