# Generated by Django 3.1 on 2020-12-22 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleeks', '0010_auto_20201222_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fleek',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='fleek',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleeks.fleek'),
        ),
    ]
