# Generated by Django 3.1 on 2020-12-22 20:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleeks', '0011_auto_20201222_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleek',
            name='anonymity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fleek',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='fleek',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
