# Generated by Django 3.1 on 2021-03-20 14:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleeks', '0012_auto_20201223_0653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fleek',
            new_name='Fleeka',
        ),
        migrations.RenameField(
            model_name='fleeksimage',
            old_name='fleek',
            new_name='fleeka',
        ),
    ]
