# Generated by Django 3.1 on 2021-03-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleeks', '0013_auto_20210321_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleeka',
            name='likes',
        ),
        migrations.DeleteModel(
            name='FleeksLike',
        ),
    ]
