# Generated by Django 3.0.8 on 2020-07-25 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20200725_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='createdBy',
        ),
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, default=0, to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
