# Generated by Django 3.0.8 on 2020-07-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20200726_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
