# Generated by Django 3.1 on 2020-10-16 06:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userfollowing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created']},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('user', 'following')},
        ),
    ]
