# Generated by Django 3.1 on 2020-12-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked'), (3, 'No_Relationship')], default=3),
        ),
    ]
