# Generated by Django 3.1 on 2020-12-02 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_follow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='related_to', through='accounts.Follow', to='accounts.Profile'),
        ),
    ]
