# Generated by Django 3.1 on 2020-12-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201202_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follows',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
