# Generated by Django 3.1 on 2021-03-09 01:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lastRefresh',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 9, 0, 0)),
        ),
    ]
