# Generated by Django 3.1 on 2021-03-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_profile_lastrefresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastRefresh',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
