# Generated by Django 3.1 on 2021-03-09 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210309_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lastRefresh',
        ),
    ]
