# Generated by Django 3.1 on 2020-12-02 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201202_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='related_to', through='authentication.Follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
