# Generated by Django 3.0.8 on 2020-07-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0002_auto_20200711_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=20, verbose_name='Longitude'),
        ),
    ]
