# Generated by Django 3.0.8 on 2020-07-14 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_auto_20200714_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-created']},
        ),
    ]
