# Generated by Django 3.1 on 2020-08-08 12:03

import discover.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0010_auto_20200806_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[500, 400], upload_to=discover.models.Product_image_path),
        ),
    ]
