# Generated by Django 3.1 on 2020-08-12 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0011_auto_20200808_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='other', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='discover.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='other'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='other', null=True, on_delete=django.db.models.deletion.CASCADE, to='discover.category'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='category',
            field=models.ForeignKey(blank=True, default='other', null=True, on_delete=django.db.models.deletion.CASCADE, to='discover.category'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
