# Generated by Django 3.1 on 2020-08-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0012_auto_20200812_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='category',
        ),
    ]
