# Generated by Django 3.1 on 2020-08-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0013_remove_purchaseitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, default='other', null=True, to='discover.Category'),
        ),
    ]
