# Generated by Django 3.1 on 2020-08-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0015_auto_20200812_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='discover.Category'),
        ),
    ]
