# Generated by Django 3.1 on 2020-09-18 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0018_viewcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewCount',
        ),
    ]
