# Generated by Django 3.1 on 2020-09-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0019_delete_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
