# Generated by Django 3.1 on 2020-09-18 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discover', '0021_viewsnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewsnumber',
            name='user',
        ),
        migrations.AddField(
            model_name='viewsnumber',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
