# Generated by Django 3.1 on 2020-09-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0022_auto_20200918_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='listed',
            field=models.BooleanField(default=False),
        ),
    ]
