# Generated by Django 3.1 on 2021-03-20 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fleeksvideo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('Description', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('publish', models.DateField()),
                ('videoUrl', models.FileField(upload_to=fleeksvideo.models.Fleeks_Video_Path)),
                ('views', models.IntegerField(default=0)),
                ('musicCoverTitle', models.CharField(max_length=120)),
                ('likesCount', models.IntegerField(default=0)),
                ('commentsCount', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
