# Generated by Django 3.1 on 2021-03-20 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleeksvideo', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleek',
            old_name='Description',
            new_name='description',
        ),
    ]
