# Generated by Django 3.1 on 2021-03-20 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fleeksvideo', '0004_fleeklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleek',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='fleek_user', through='fleeksvideo.FleekLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
